Comunidad\UsuariosBundle\Entity\Users:
    type: entity
    repositoryClass: Comunidad\UsuariosBundle\Repository\UsersRepository
    table: users
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: AUTO
    fields:
        login:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        email:
            type: string
            length: '255'
            unique: true
        salt:
            type: string
            length: '64'
        roles:
            type: string
            length: '255'
        #lifecycleCallbacks: {  }
