#usuarios_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: UsuariosBundle:Default:index }
recetas:
    pattern: /recipes/{id}
    defaults: { _controller: UsuariosBundle:Recipe:showid }
    #requirements : \d+
recetas_seo:
    pattern: /recetas/{name}
    defaults: { _controller: UsuariosBundle:Recipe:showname }
homepage:
    pattern: /
    defaults: {_controller: UsuariosBundle:Default:index}
pagina_estatica:
    pattern: /estaticas/{pagina}
    defaults: {_controller: UsuariosBundle:Default:estatica}

usuarios_registro_create:
    pattern: /usuarios/registro
    defaults: {_controller:UsuariosBundle:Usuarios:create}
usuarios_create_show:
    pattern: /usuarios/show
    defaults: {_controller:UsuariosBundle:Usuarios:show}
usuarios_edit:
    pattern: /usuarios/editar/{id}
    defaults: {_controller:UsuariosBundle:Usuarios:edit}
usuarios_listado:
    pattern: /usuarios/listado
    defaults: {_controller:UsuariosBundle:Usuarios:listado}



usuarios_mensaje_listar:
    pattern: /mensaje/listado
    defaults: {_controller:UsuariosBundle:Mensajes:listado}
usuarios_mensaje_create:
    pattern: /mensaje/nuevo
    defaults: {_controller:UsuariosBundle:Mensajes:create}
usuarios_mensaje_edit:
    pattern: /mensaje/editar/{id}
    defaults: {_controller:UsuariosBundle:Mensajes:edit}

admin:
    pattern: /admin
    defaults: {_controller:UsuariosBundle:Admin:index}
login:
    pattern:   /login
    defaults:  { _controller: UsuariosBundle:Admin:login }
login_check:
    pattern:   /login_check
#logout:
#    path:   /logout