#usuarios_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: UsuariosBundle:Default:index }
recetas:
    pattern: /{_locale}/recipes/{id}
    defaults: { _controller: UsuariosBundle:Recipe:showid }
    requirements : 
     _locale: en|es
recetas_seo:
    pattern: /{_locale}/recetas/{name}
    defaults: { _controller: UsuariosBundle:Recipe:showname }
    requirements : 
     _locale: en|es
homepage:
    pattern: /
    defaults: {_controller: UsuariosBundle:Default:index}
pagina_estatica:
    pattern: /{_locale}/estaticas/{pagina}
    defaults: {_controller: UsuariosBundle:Default:estatica}
    requirements : 
     _locale: en|es

usuarios_registro_create:
    pattern: /{_locale}/usuarios/registro
    defaults: {_controller:UsuariosBundle:Usuarios:create}
    requirements : 
     _locale: en|es
usuarios_create_show:
    pattern: /{_locale}/usuarios/show
    defaults: {_controller:UsuariosBundle:Usuarios:show}
    requirements : 
     _locale: en|es
usuarios_edit:
    pattern: /admin/usuarios/editar/{id}
    defaults: {_controller:UsuariosBundle:Usuarios:edit}
    requirements : 
     _locale: en|es
usuarios_listado:
    pattern: /{_locale}/usuarios/listado
    defaults: {_controller:UsuariosBundle:Usuarios:listado}
    requirements : 
     _locale: en|es

usuarios_inbox:
    pattern: /{_locale}/usuarios/inbox
    defaults: {_controller:UsuariosBundle:Usuarios:inbox}
    requirements : 
     _locale: en|es

_usuarios_inbox:
    pattern: /usuarios/inbox
    defaults: {_controller:UsuariosBundle:Usuarios:inbox}
    

admin:
    pattern: /admin
    defaults: {_controller:UsuariosBundle:Admin:index}

_admin:
    pattern: /admin/
    defaults: {_controller:UsuariosBundle:Admin:index}

registro:
    pattern: /{_locale}/registro
    defaults: { _controller: UsuariosBundle:Usuarios:registro}
    requirements : 
     _locale: en|es

login:
    pattern:   /{_locale}/login
    defaults:  { _controller: UsuariosBundle:Admin:login }
    requirements : 
     _locale: en|es
login_check:
    pattern:   /login_check
logout:
    pattern: /logout
    