comunidad_mensajes_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ComunidadMensajesBundle:Default:index }
usuarios_mensaje_listar:
    pattern: /{_locale}/mensaje/listado
    defaults: {_controller:MensajesBundle:Mensajes:listado}
    requirements : 
     _locale: en|es

usuarios_mensaje_send:
    pattern: /mensaje/listado/{id}
    defaults: {_controller:MensajesBundle:Mensajes:send}
    
usuarios_mensaje_create:
    pattern: /{_locale}/mensaje/nuevo
    defaults: {_controller:MensajesBundle:Mensajes:create}
    requirements : 
     _locale: en|es
usuarios_mensaje_edit:
    pattern: /{_locale}/mensaje/editar/{id}
    defaults: {_controller:MensajesBundle:Mensajes:edit}
    requirements : 
     _locale: en|es