security:
    providers:
        #in_memory:
        #    memory:
        #     users:
        #      ryan:  { password: ryanpass, roles: 'ROLE_USER' }
        #      admin: { password: kitten, roles: 'ROLE_ADMIN' }
        users:
            entity: { class: UsuariosBundle:Users, property: login }

    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        Comunidad\UsuariosBundle\Entity\Users:
         #id: sha256salted_encoder
         algorithm:        sha1
         encode_as_base64: false
         iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    firewalls:
        secured_area:
            pattern:    ^/
            provider: users
            anonymous: ~
            form_login: 
                login_path:  login
                check_path:  login_check
            logout: 
             path: logout
             target: /
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~

    access_control:
     #- { path: ^/admin, roles: ROLE_ADMIN }
     - { path: ^/admin, roles: ROLE_ADMIN }
