security:
    providers:
        in_memory:
            memory:
             users:
              ryan:  { password: ryanpass, roles: 'ROLE_USER' }
              admin: { password: kitten, roles: 'ROLE_ADMIN' }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
        secured_area:
         pattern: ^/
         anonymous: ~
         #http_basic:
          #realm: "Usuarios"
         form_login:
          login_path: login_path
          check_path: login_check
         logout: ~

    access_control:
     - { path: ^/admin, roles: ROLE_ADMIN }
